export const TIME_TO_CONSIDER_APP_IDLE = 10000;
export const TIME_BETWEEN_IDLE_ANIMATIONS_LOW_DENSITY = 5000;
export const TIME_BETWEEN_IDLE_ANIMATIONS_MEDIUM_DENSITY = 3000;
export const TIME_BETWEEN_IDLE_ANIMATIONS_HIGH_DENSITY = 2000;
export const UNLOADED_ID = 'unloaded';
